# Generated by Django 3.2.3 on 2021-06-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alarm_ack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='ack',
        ),
    ]
