# Generated by Django 3.2.3 on 2021-06-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_alarm_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgement',
            name='alarm',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.alarm'),
            preserve_default=False,
        ),
    ]
